[server]
port = 8501
address = "0.0.0.0"
headless = true
maxUploadSize = 200
enableCORS = false
enableXsrfProtection = true

[browser]
gatherUsageStats = false
serverAddress = "localhost"
serverPort = 8501

[theme]
base = "light"
primaryColor = "#FF0050"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F5F5F5"
textColor = "#262626"
font = "sans serif"

[runner]
magicEnabled = true
installTracer = false
fixMatplotlib = true